apiVersion: v2
name: dummy
description: A Helm chart for Semantic Release Playground - A playground for semantic-release automation
type: application
version: 1.1.1
appVersion: "1.3.2"
keywords:
  - dummy
home: https://github.com/ardikabs/semantic-release-playground
sources:
  - https://github.com/ardikabs/semantic-release-playground
maintainers:
  - name: ardikabs
    email: me@ardikabs.com
