name: CI

on:
  push:
    branches:
      - main
      - "release/v*"
    paths-ignore:
      - README.md
      - charts/**
      - hack/CHART_README.md.gotmpl

  pull_request:
    branches:
      - main
      - "release/v*"
    paths:
      - app/**

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Lint Code
        run: echo "Linting code..."

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: echo "Build code..."

  tests:
    name: Tests
    needs: [lint, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run E2E Tests
        run: echo "Running end-to-end tests..."
