name: Release

run-name: >-
  ${{
    github.event_name == 'workflow_dispatch' && format('🚀 Manual Release: {0}', github.event.inputs.reason) ||
    github.event_name == 'push' && format('🛠️ Maintenance Patch: {0}', github.ref_name) ||
    github.event_name == 'workflow_run' && format('🧪 RC Release: {0}', github.event.workflow_run.head_branch) ||
    format('📦 Release - {0}', github.event.repository.updated_at)
  }}
on:
  push:
    branches:
      - "release/v*"

  workflow_run:
    workflows: ["CI"] # Must match the 'name' of Workflow A
    branches:
      - main
    types:
      - completed

  workflow_dispatch:
    inputs:
      reason:
        description: 'Provide a enough description for this release (e.g., "Release v1.5 <codename>").'
        required: true
        default: 'Next Release'

jobs:
  verification:
    name: Verification
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.decision.outputs.run }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Release Decision
        id: decision
        run: |
          chmod +x hack/release-gate.sh
          ./hack/release-gate.sh \
            --event "${{ github.event_name }}" \
            --ref "${{ github.ref }}" \
            --ref-name "${{ github.ref_name }}" \
            --branch "${{ github.event.workflow_run.head_branch }}" \
            --message "${{ github.event.workflow_run.head_commit.message }}"

  release:
    name: Release
    needs: [verification]
    if: needs.verification.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    env:
      IS_MANUAL_RELEASE: ${{ github.event_name == 'workflow_dispatch' }}
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_git_sha_short: ${{ steps.semantic.outputs.new_release_git_sha_short }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install Helm Docs
        uses: gabe565/setup-helm-docs-action@v1
        with:
          version: v1.14.2

      - name: Setup Semantic Release Config for App
        run: |
          # if [[ "${{ github.event_name }}" == "workflow_run" ]]; then
          #   echo "Using RC configuration"
          #   cp .github/releaserc/rc.releaserc.yml .releaserc.yml
          # else
          #   echo "Using Stable configuration"
          #   cp .github/releaserc/stable.releaserc.yml .releaserc.yml
          # fi
          # cat .releaserc.yml

          cp .github/releaserc/releaserc.js .releaserc.js

      - name: Semantic Release (App)
        id: semantic
        uses: cycjimmy/semantic-release-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          semantic_version: 24
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/exec
            conventional-changelog-conventionalcommits

  publish-image:
    name: Publish Container
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.new_release_published == 'true'
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata
        if: needs.release.outputs.new_release_published == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ needs.release.outputs.new_release_version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.release.outputs.new_release_version }}

      - name: Set up QEMU
        if: needs.release.outputs.new_release_published == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: needs.release.outputs.new_release_published == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: needs.release.outputs.new_release_published == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Packaging App
        if: needs.release.outputs.new_release_published == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ needs.release.outputs.new_release_version }}
            COMMIT_HASH=${{ needs.release.outputs.new_release_git_sha_short }}
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
